- hosts: master
  remote_user: root
  tasks:

    - name: set hadoop home
      lineinfile: state=present dest=/home/hadoop/.bash_profile line='HADOOP_HOME=/usr/local/hadoop'
    - name: set mapred home
      lineinfile: state=present dest=/home/hadoop/.bash_profile line='HADOOP_MAPRED_HOME=$HADOOP_HOME'
    - name: set hdfs home
      lineinfile: state=present dest=/home/hadoop/.bash_profile line='HADOOP_HDFS_HOME=$HADOOP_HOME'
    - name: set yarn home
      lineinfile: state=present dest=/home/hadoop/.bash_profile line='YARN_HOME=$HADOOP_HOME'
    - name: set java home
      lineinfile: state=present dest=/home/hadoop/.bash_profile line='JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.60-2.b27.el7_1.x86_64'
    - name: append hadoop home to path
      lineinfile: state=present dest=/home/hadoop/.bash_profile line='PATH=$PATH:$HADOOP_HOME'
